# TODO: complete the compile commands

all: nbody_serial_nocells nbody_omp_cells

nbody_serial_nocells: nbody_serial_nocells.cpp
	#FILL IN COMPILE COMMAND HERE

nbody_omp_cells: nbody_omp_cells.cpp
	#FILL IN COMPILE COMMAND HERE

clean:
	rm -f nbody_serial_nocells nbody_omp_cells 
